name: Code Linter

on:
  push:
    paths:
      - '**/*.py'
      - '**/*.txt'
      - '.github/workflows/linter.yml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir uv
          uv pip install --no-cache-dir flake8 pylint vulture -r requirements.txt -q --system

      - name: Run flake8
        run: flake8 $(git ls-files '*.py') --max-line-length 180 --max-doc-length 180 --ignore=E203,E402,E501,W505 --doctests --statistics
        continue-on-error: true

      - name: Run PyLint
        run: pylint $(git ls-files '*.py') --max-line-length 180 --disable=C0114,C0115,C0116,W0212,C0411,C0413,R0801,R0902,R0903,R0904,R0911,R0912,R0913,R0914,R0915,R0916,R0917,E1101
        continue-on-error: true

      - name: Run Vulture
        run: vulture $(git ls-files '*.py')
        continue-on-error: true
